vim.keymap.set('n', '<F3>', function()
  vim.lsp.buf.code_action({apply=true})
end, {})
vim.keymap.set('n', '<leader>fe', function()
	vim.cmd(':NvimTreeToggle')
end, {})
end, {})
vim.keymap.set('n', '<leader>gg', function()
	vim.cmd(':Neogit')
end, {})
vim.keymap.set('n', '<F12>', function()
  vim.cmd(':cclose')
end,{})
vim.keymap.set('n', '<Leader>db', function()
  vim.cmd(':NvimTreeClose')
  require("dapui").toggle()
end,{})
vim.keymap.set('n', '<F8>', function()
  local status_ok, _ = pcall( vim.cmd, ':cn')
  if status_ok == false then
    vim.cmd(':crewind')
  end
end,{})
vim.keymap.set('n', '<F9>', function()
  require('dap').toggle_breakpoint()
end,{})
vim.keymap.set('n', '<F11>', function()
  require('dap').step_into()
end,{})
vim.keymap.set('n', '<F10>', function()
  require('dap').step_over()
end,{})
local async_command = 'cmake --build build --target all'
vim.keymap.set('n', '<F7>', function()
  vim.cmd(':copen')
  vim.cmd(':AsyncRun ' .. async_command)
end,{})
vim.keymap.set('n', '<F2>', function()
  vim.ui.input({ prompt = 'Enter makeprg command: ' }, function(input)
    async_command = input
  end)
end,{})
vim.keymap.set('n', '<S-F7>', function()
  vim.cmd(':cclose')
end,{})
vim.keymap.set('n', '<Leader>tt', function()
  vim.cmd([[
  :bo split
  :term
  ]])
end,{})
