set -g default-terminal "tmux-256color"
set -g mouse on
set -g extended-keys on
set -g extended-keys-format csi-u

set-option -sa terminal-overrides ",xterm*:Tc"
setw -g mode-keys vi
bind  c  new-window      -c "#{pane_current_path}"
bind  %  split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"
bind 'J' resize-pane -D 10
bind 'T' display-popup -E tmux-sessionizer.sh
bind 'o' display-popup -E opencode_switch.py
bind -n Home send-keys Escape "[H"
bind -n End  send-keys Escape "[F"

# vim-tmux-navigator (inlined from christoomey/vim-tmux-navigator)
is_vim="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ ]+ +(\S+/)?g?\.(view|l?n?vim?x?|fzf)(diff)?(-wrapped)?$'"
bind-key -n C-h if-shell "$is_vim" "send-keys 'C-h'" "select-pane -L"
bind-key -n C-j if-shell "$is_vim" "send-keys 'C-j'" "select-pane -D"
bind-key -n C-k if-shell "$is_vim" "send-keys 'C-k'" "select-pane -U"
bind-key -n C-l if-shell "$is_vim" "send-keys 'C-l'" "select-pane -R"
bind-key -n 'C-\' if-shell "$is_vim" "send-keys 'C-\\'" "select-pane -l"
bind-key -T copy-mode-vi C-h select-pane -L
bind-key -T copy-mode-vi C-j select-pane -D
bind-key -T copy-mode-vi C-k select-pane -U
bind-key -T copy-mode-vi C-l select-pane -R
bind-key -T copy-mode-vi 'C-\' select-pane -l
bind C-l send-keys 'C-l'

gray_light="#D8DEE9"
gray_dark="#3B4252"
green="#8EBD6B"
cyan="#48B0BD"
blue="#4FA6ED"
white="#FFFFFF"

set -g status-position top
set -g status-left-length 100
set -g status-style "fg=${gray_light},bg=default"
set -g status-left "#[fg=${green},bold]  #S #[fg=${gray_light},nobold]|"
set -g window-status-current-format "#[fg=${cyan}]  #[fg=${cyan},bold,underscore]#I:#W"
set -g window-status-format " #I:#W"
set -g mode-style "fg=${gray_dark},bg=${cyan}"
set -g message-style "fg=${gray_light},bg=default"
set -g pane-border-style "fg=${gray_dark}"
set -g pane-active-border-style "fg=${gray_light}"
